import { Open_Sans } from "next/font/google";
import "./globals.scss";
import Navbar from "@/Components/Navbar/Navbar";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Gurvinder Singh's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
